inherit_from:
  - .rubocop_todo.yml
  - .rubocop-rails.yml

AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

require:
  - rubocop-discourse


# Set the preferred style guide
inherit_from:
  - .rubocop_todo.yml
  # Add other inherited configuration files as needed

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

# Syntax
Style/FrozenStringLiteralComment:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: percent
